sequenceDiagram
    participant przeglądarka
    participant serwer

    Note right of przeglądarka: Formularz HTML z method="POST" i action="/new_note"
    przeglądarka->>serwer: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    Note left of serwer: Serwer dodaje notatkę do tablicy notes
    serwer-->>przeglądarka: HTTP 302 Przekierowanie do /notes

    przeglądarka->>serwer: GET https://studies.cs.helsinki.fi/exampleapp/notes
    serwer-->>przeglądarka: Dokument HTML
    przeglądarka->>serwer: GET  https://studies.cs.helsinki.fi/exampleapp/main.css
    serwer-->>przeglądarka: Plik CSS

    przeglądarka->>serwer: GET  https://studies.cs.helsinki.fi/exampleapp/main.js
    serwer-->>przeglądarka: Plik JavaScript

    Note right of przeglądarka: Przeglądarka wykonuje kod JavaScript, który pobiera dane notatek

    przeglądarka->>serwer: GET  https://studies.cs.helsinki.fi/exampleapp/data.json
    serwer-->>przeglądarka: Aktualizuje plik JSON, który zawiera nową notatkę

    Note right of przeglądarka: Przeglądarka renderuje zaktualizowaną listę notatek
